### ISSUE TITLE
Saving files to Cloud

### ISSUE THREAD

**Issue by rezpower** [ruinernin/foxystreams#15]
Hi ruinernin

I love Foxystreams and would like to thank you for it :) I just have one little question. I am using Foxystreams with my Premiumize account and all is working fine. Only thing is that when I search for a cached video I want to be able to save it on my cloud. With Foxystreams I am able to play it with no problem but there is no way to save on PM Cloud. Is it possible for you to add an option (like in FEN or SEREN) to be able to save cached files to cloud. Even if there is a workaround to b able to copy magnet link, it would be great, so we can manually download a file we want to keep :)

**Comment by ruinernin** [comment]
Sure, this is easily enough done I think.

Would you see this as a global switch where all played items are added or as a prompt per play?

**Comment by rezpower** [comment]
Hey  thanks a lot for your response :)
I personally believe that just an option in context menu ( i mean the long click on the file name) to save file to cloud. Right now when you long click (or right click in windows) this is what we have: (Play, Mark as watched, Play from here and add to favorites ). A "Save to cloud" option here would be best I guess. 
But at the end please do whatever is doable and less difficult.
By Just giving us  the possibility to save files to cloud, foxystreams will be a killer addon for me :)

**Comment by ruinernin** [comment]
Thanks for clarifying. I think the contextmenu item makes the most sense here overall but also adding a settings switch for prompt per play won't be difficult either (and would work playing from a meta-like addon). I'll look at doing the latter first.

Thanks for the suggestion.

**Comment by brentonv** [comment]
Hey ruinernin just a quick thanks for your add-on mate. Foxy streams is my favourite by far. Good to see you back.

**Comment by rezpower** [comment]
Thanks a lot for the time and effort you put in this. There are so many addons out there but foxystreams remains my main and favorite addon.

**Comment by rezpower** [comment]
ruinernin  please don't forget us :) 
waiting for this for so long. I really don't want to be pushing it or insisting etc..
Just want to make sure you didn't forget me! :)

**Comment by ruinernin** [comment]
@rezpower Not forgotten! This is a solo project when I get time, expect an update on this later in the week.
