### ISSUE TITLE
Retry or timeout delay

### ISSUE THREAD

**Issue by brentonv** [ruinernin/foxystreams#16]
Hi @ruinernin just wondering if you are aware of this issue. It's nothing major but quite often I have to click the title again for it to play. The first attempt often fails but picks it up on the second try. Could you maybe add a retry on timeout kinda thingy? Thanks mate!

**Comment by ruinernin** [comment]
Yep it's something I'm aware of and haven't been able to track down, it has failed silently on me any time I have reproduced it. I've noticed it appears to occur more frequently on faster devices (PC vs an Android device).

If you can get any log information when this error occurs I'd be greatful. I suspect it's a race condition somewhere underneath, I'm reluctant to add an artificial delay but maybe it's the best course of action if it's causing UX issues.

**Comment by brentonv** [comment]
I'm usually running on winx64 Xbox so yeah compared to my armv7 firestick there's a big difference in power.  But i'm fairly certain it happens on both, but like you said it's infrequent. I don't think it's even happened again since I logged this request however I'll try to capture a log file if it reoccurs. 

Absolutely love your work on this, however simple it is it's the best add-on. Thanks mate!

**Comment by ruinernin** [comment]
I believe the commit above will address this.

**Comment by brentonv** [comment]
@ruinernin thanks heaps mate. Along with the new cloud saving this add-on kills it.
