### ISSUE TITLE
Alldebrid support - migration to apiv4

### ISSUE THREAD

**Issue by Alldebrid** [ruinernin/foxystreams#17]
Hello,

We are the Alldebrid staff. We are contacting you today about an update regarding our API.

We will disable our old API at the end of the month.

Documentation for the last API is here : https://docs.alldebrid.com/v4/ . This API should be the final version and should not change much in the futur.

Let us know if you need more information or any help.

**Comment by ruinernin** [comment]
Added a suffix in 4e95264ccd2a9ee5ef0a043d7f8146c47342c749, seems correct. I do not have an account to test with.

@Alldebrid if more changes are necessary for this to work, PRs are welcome.
