### ISSUE TITLE
Add cached torrent to cloud works only for first torrent!

### ISSUE THREAD

**Issue by rezpower** [ruinernin/foxystreams#18]
Hi,
I wanted to let you know that when you use the add to cloud option the first file works fine.
Then if you choose a second file in the same search and try to add it to cloud you get a message
saying : failed to add file to cloud.

I also just realized that wrong file was saved to cloud. (this happened today: I saved a file and the file that was saved was not the one I chose, but another file from the search result!)

**Comment by ruinernin** [comment]
Ah, made a mistake in the iteration cleaning up after testing. Should be fixed in 18003027f86025614fdccf22151e1eba73da0e3e

**Comment by rezpower** [comment]
Yes it's fixed now :) added 3 consecutive files to cloud from same search and all are saved.
 thanks again :)

**Comment by ruinernin** [comment]
Thanks for confirming it's fixed.

**Comment by brentonv** [comment]
Does anyone want to explain to me what advantage this has? Is it just to keep an online library?

**Comment by ruinernin** [comment]
Essentially add a bookmark but also depending on the debrid provider (Premiumize for sure) will mean the file should stay available and not be garbage collected.

**Comment by rezpower** [comment]
> 
> 
> Does anyone want to explain to me what advantage this has? Is it just to keep an online library?

I personally collection and keep some of the movies I find great. Not specially on cloud but I download them and keep them locally. Also most of the time I do not have the time to watch a movie just when I find it! By adding it to my cloud I make sure it's available later when I have time and want to watch it and its not deleted already from cache.
