### ISSUE TITLE
Search box fails using ActivateWindow

### ISSUE THREAD

**Issue by brentonv** [ruinernin/foxystreams#21]
Hey there @ruinernin just a small detail I'm hoping you can look into? I used to have a working built-in function to search FoxyStreams from the skin `ActivateWindow(Videos,"plugin://plugin.video.foxystreams/?mode=search")` and this used to work fine until a while ago.

If search is called from `ActivateWindow` the search box opens and when you submit a search the results show in the background but are unusable because the search box re-opens? If you back out of the second search box it exits the addon, and the same if you re-enter another search query. The behavior is the same for both search API's.

The search function works fine when used from within the addon itself.  I wonder if it might be related to any changes made with issues #19  and #20 ... When you have the time could you please look into this. Thanks mate

**Comment by ruinernin** [comment]
Cleaning up old issues, if this is still a thing do re-open.
