### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by mrXoo** [ruinernin/foxystreams#22]
Hi There, Just Stumbled upon this great addon.

I am wondering if you would be able to add RD Downloads to the menu. Right now I see there is RD torrent downloads, but it would be great if we could have all our downloads as well  

Cheers and thanks

**Comment by ruinernin** [comment]
I believe there are/were other add-ons that provide much a much better interface to debrid services which would probably cover this.

If those are no longer supported or working it may be worth forking this or using the API implementation as a starting point to building an addon to do this.

One of the aims of this addon is to provide as few features as possible while being useful, that said if there's no other basic plugin currently providing that functionality it should be a consideration. Please re-open the issue if so.

**Comment by mrXoo** [comment]
I believe this folder is actually found in foxymeta. I really need that folder displayed because it enables me to do bulk automatic downloads from RD. Your 2 addons are a little known gem. Let me know if you would be interested in some ideas i have for them :) 
I can access this folder from foxymeta so no need right now. Thanks
