### ISSUE TITLE
Kodi 19 Compatibility? 

### ISSUE THREAD

**Issue by KilgoreTrout530** [ruinernin/foxystreams#24]
Hey, I was just wondering if you were working on compatibility for Kodi 19.

**Comment by Arthur1967** [comment]
I certainly hope it is going to be 19 compatible sometime it's a great Add on although I'm going to give 19 a few months because I used it and then it started messing up so I went back to 18.9 for now but it worked fabulous until it messed up for me￼￼

**Comment by ghost** [comment]
I updated the add-on myself and tested it on multiple devices with Real-Debrid. You can download it from here: https://github.com/nemoandcrush/foxystreams/releases/tag/0.2.9

**Comment by nemoandcrush** [comment]
I need to make some changes, please wait until tomorrow..

> I tried to make the changes myself. I have it working now but only tested for Real-Debrid. You can download it from here: https://github.com/nemoandcrush/foxystreams/releases/tag/0.2.8

I need to make some changes currently not working. WIll update tomorrow

**Comment by Arthur1967** [comment]
> I updated the add-on myself and tested it on multiple devices with Real-Debrid. You can download it from here: https://github.com/nemoandcrush/foxystreams/releases/tag/0.2.9
> 
> 
> 
> 
> 
> 

￼how often does the list update its working great on 19 thanks

**Comment by rezpower** [comment]
> 
> 
> I updated the add-on myself and tested it on multiple devices with Real-Debrid. You can download it from here: https://github.com/nemoandcrush/foxystreams/releases/tag/0.2.9

It's working perfect with premiumize also. Thanks a lot :)

**Comment by Arthur1967** [comment]
Will it work on Kodi 18.9  to thank you for updating it I follow you

**Comment by brentonv** [comment]
@Arthur1967 @rezpower hey guys does anyone have a working Kodi19 fork?

**Comment by ruinernin** [comment]
Belatedly pushed Matrix compatible update.

**Comment by brentonv** [comment]
Thanks very much @ruinernin :+1:
