### ISSUE TITLE
Kodi 19

### ISSUE THREAD

**Issue by Arthur1967** [ruinernin/foxystreams#26]
I wish you would bring this back it’s a great add-on thank you

**Comment by drinfernoo** [comment]
It's already been updated for Matrix...

**Comment by Arthur1967** [comment]
What is the repo for it then I tried getting it from the masters zip there
was no repository so could you send it to me Thank you

**Comment by Arthur1967** [comment]
I just want to know how to install it is I used to use it all the time
thanks

**Comment by Arthur1967** [comment]
I figured it out thank you you can close this now
