### ISSUE TITLE
Foxystreams

### ISSUE THREAD

**Issue by Arthur1967** [ruinernin/foxystreams#28]
Is there anyway you can add next page like it used to have in the past ,so you can go to another page on the list Just wondering thank you

**Comment by ruinernin** [comment]
I don't think anything has changed here? This might be something in lists in the foxymeta plugin?

**Comment by Arthur1967** [comment]
I just rolled it back to the earlier version and it works fine the 030 or whatever it was the newest version I can't get to work and I can't figure out how to share my log file with you so I just went to the previous version and it works fine thank you
