### ISSUE TITLE
List

### ISSUE THREAD

**Issue by Arthur1967** [ruinernin/foxystreams#29]
Is there anyway you can add next page to list on foxy streams like it used to have if that's not too much trouble Unrelated question is open wizard still being maintained because that's what I use if not which one do you Recommend thank you

**Comment by drinfernoo** [comment]
OpenWizard is no longer being maintained.

**Comment by Arthur1967** [comment]
Damn I like that one too it was easy to use now I gotta make a decision on which one to use thank you
