### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by Arthur1967** [ruinernin/foxystreams#34]
I certainly hope you stay on GitHub and so does seren As some have disappeared recently thank you

**Comment by chrisdlees** [comment]
Might as well jump on this to say, I really appreciated how the quick start guide ends with the "now you can watch Night of the Living Dead" bit. Sassy towards the standard metadata string in ALLLLLLL the right ways lol
Edit: Damn Arthur, you've had a LOT of issues. Makes me skittish to be in an Issue you OP'd.
