### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Arthur1967** [ruinernin/foxystreams#35]
I see that you are a contributor to Seren every time I open kodi my trakt Starts re-sinking I know this isn't the right spot but I don't know who to get a hold of detail thank you

**Comment by drinfernoo** [comment]
Why would you open an issue here for a completely separate add-on?

**Comment by Arthur1967** [comment]
Because there is no way to contact Nixgates And I thought you were helping maintain it sorry

**Comment by chrisdlees** [comment]
lol "re-sinking"
