### ISSUE TITLE
Addon self update cool feature

### ISSUE THREAD

**Issue by dobbelina** [ruinernin/foxystreams#6]
Hi ruinernin!

I browsed your repo and noticed the **extension point="xbmc.addon.repository"** 
in the plugin.video.foxystreams addon.xml.
Cool feature that it updates itself, i wasn't aware that you could do that.
Only caveat is off course if you got dependencies only supplied by your repo.
Then it wont work standalone on a fresh install.

Have a good day 😄

**Comment by ruinernin** [comment]
Thanks!
